name: ECommands
main: cat.nyaa.ecommands.SpigotLoader
version: ${project.version}
api-version: 1.18
depend:
  - ECore
softdepend:
  - Essentials
commands:
  pay:
    usage: /pay <amount|confirm|cancel|show|help> [player...]
    description: Transfer money to other players.
    permission: ecommands.pay
    permission-message: You don't have permission to use this command.
  eco:
    usage: /eco <player|system> <deposit|withdraw|set> <amount> [players...]
    description: administration commands about economy
    permission: ecommands.eco
    permission-message: You don't have permission to use this command.
  ecommands:
    usage: /ecommands reload
    description: reload the ecommands config(language) file
    permission: ecommands.reload
    permission-message: You don't have permission to use this command.
  balance:
    usage: /balance [player]
    description: check player balance
    permission: ecommands.balance.self
    permission-message: You don't have permission to use this command.